Avoid blacksmith error with Ruby 1.8.7
With 1.8.7, an exception is generated by ruby if blacksmith is present:

```
rake aborted!
NoMethodError: undefined method `upcase' for :major:Symbol
puppet-puppet/Rakefile:9:in `require'
puppet-puppet/Rakefile:9
(See full trace by running task with --trace)
```

This commit ignores that error if Ruby 1.8.7 is being used.